name: First Workflow # Workflow name

on:
  push: # Trigger workflow on every push

jobs:
  first-job: # Define a job
    runs-on: ubuntu-latest # Use an Ubuntu virtual machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # Get the latest code

      - name: Print Hello World
        run: echo "Hello, GitHub Actions!" # Run a command
